
#pragma once

#ifdef PLATFORM_QT
 #include <QOpenGLFunctions>
 extern QOpenGLFunctions* gl;
 #define glActiveTexture (gl->glActiveTexture)
 #define glAttachShader (gl->glAttachShader)
 #define glBindBuffer (gl->glBindBuffer)
 #define glBindFramebuffer (gl->glBindFramebuffer)
 #define glBindRenderbuffer (gl->glBindRenderbuffer)
 #define glBindTexture (gl->glBindTexture)
 #define glBlendFunc (gl->glBlendFunc)
 #define glBufferData (gl->glBufferData)
 #define glCheckFramebufferStatus (gl->glCheckFramebufferStatus)
 #define glClear (gl->glClear)
 #define glClearColor (gl->glClearColor)
 #define glCompileShader (gl->glCompileShader)
 #define glCreateProgram (gl->glCreateProgram)
 #define glCreateShader (gl->glCreateShader)
 #define glCullFace (gl->glCullFace)
 #define glDeleteBuffers (gl->glDeleteBuffers)
 #define glDeleteFramebuffers (gl->glDeleteFramebuffers)
 #define glDeleteProgram (gl->glDeleteProgram)
 #define glDeleteRenderbuffers (gl->glDeleteRenderbuffers)
 #define glDeleteShader (gl->glDeleteShader)
 #define glDeleteTextures (gl->glDeleteTextures)
 #define glDisable (gl->glDisable)
 #define glDisableVertexAttribArray (gl->glDisableVertexAttribArray)
 #define glDrawArrays (gl->glDrawArrays)
 #define glDrawElements (gl->glDrawElements)
 #define glEnable (gl->glEnable)
 #define glEnableVertexAttribArray (gl->glEnableVertexAttribArray)
 #define glFramebufferRenderbuffer (gl->glFramebufferRenderbuffer)
 #define glFramebufferTexture2D (gl->glFramebufferTexture2D)
 #define glGenBuffers (gl->glGenBuffers)
 #define glGenerateMipmap (gl->glGenerateMipmap)
 #define glGenFramebuffers (gl->glGenFramebuffers)
 #define glGenTextures (gl->glGenTextures)
 #define glGetAttribLocation (gl->glGetAttribLocation)
 #define glGetIntegerv (gl->glGetIntegerv)
 #define glGetProgramInfoLog (gl->glGetProgramInfoLog)
 #define glGetProgramiv (gl->glGetProgramiv)
 #define glGenRenderbuffers (gl->glGenRenderbuffers)
 #define glGetShaderInfoLog (gl->glGetShaderInfoLog)
 #define glGetShaderiv (gl->glGetShaderiv)
 #define glGetShaderSource (gl->glGetShaderSource)
 #define glGetUniformLocation (gl->glGetUniformLocation)
 #define glLineWidth (gl->glLineWidth)
 #define glLinkProgram (gl->glLinkProgram)
 #define glPixelStorei (gl->glPixelStorei)
 #define glRenderbufferStorage (gl->glRenderbufferStorage)
 #define glShaderSource (gl->glShaderSource)
 #define glTexImage2D (gl->glTexImage2D)
 #define glTexParameteri (gl->glTexParameteri)
 #define glUniform1f (gl->glUniform1f)
 #define glUniform2f (gl->glUniform2f)
 #define glUniform3f (gl->glUniform3f)
 #define glUniform4f (gl->glUniform4f)
 #define glUniform1i (gl->glUniform1i)
 #define glUniformMatrix4fv (gl->glUniformMatrix4fv)
 #define glUseProgram (gl->glUseProgram)
 #define glVertexAttrib3f (gl->glVertexAttrib3f)
 #define glVertexAttrib4f (gl->glVertexAttrib4f)
 #define glVertexAttribPointer (gl->glVertexAttribPointer)
 #define glViewport (gl->glViewport)
#endif
